-- DULCES MOMENTOS - BASE DE DATOS SUPABASE
-- Ejecuta TODO este archivo en Supabase > SQL Editor > New query > Run.

create table if not exists public.allowed_emails (
  email text primary key
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text,
  sale_price numeric(12,2) not null default 0 check (sale_price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory_batches (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  lot_code text not null,
  qty_initial integer not null check (qty_initial > 0),
  qty_available integer not null check (qty_available >= 0),
  unit_cost numeric(12,2),
  entered_at date not null default current_date,
  expires_at date not null,
  note text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique(product_id, lot_code)
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.inventory_batches(id),
  product_id bigint not null references public.products(id),
  qty integer not null check (qty > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  sold_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

alter table public.allowed_emails enable row level security;
alter table public.products enable row level security;
alter table public.inventory_batches enable row level security;
alter table public.sales enable row level security;

create or replace function public.is_allowed_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.allowed_emails a
    where lower(a.email) = lower(coalesce(auth.jwt()->>'email',''))
  );
$$;

revoke all on function public.is_allowed_user() from public;
grant execute on function public.is_allowed_user() to authenticated;

drop policy if exists products_allowed on public.products;
create policy products_allowed on public.products
for all to authenticated
using (public.is_allowed_user())
with check (public.is_allowed_user());

drop policy if exists batches_allowed on public.inventory_batches;
create policy batches_allowed on public.inventory_batches
for all to authenticated
using (public.is_allowed_user())
with check (public.is_allowed_user());

drop policy if exists sales_allowed_select on public.sales;
create policy sales_allowed_select on public.sales
for select to authenticated
using (public.is_allowed_user());

create or replace function public.register_sale(
  p_batch_id bigint,
  p_qty integer,
  p_unit_price numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_batch public.inventory_batches%rowtype;
begin
  if not public.is_allowed_user() then
    raise exception 'Usuario no autorizado';
  end if;

  if p_qty is null or p_qty <= 0 then
    raise exception 'Cantidad inválida';
  end if;

  select * into v_batch
  from public.inventory_batches
  where id = p_batch_id
  for update;

  if not found then
    raise exception 'Lote no encontrado';
  end if;

  if v_batch.qty_available < p_qty then
    raise exception 'Stock insuficiente';
  end if;

  if v_batch.expires_at < current_date then
    raise exception 'No se puede vender un lote vencido';
  end if;

  update public.inventory_batches
  set qty_available = qty_available - p_qty
  where id = p_batch_id;

  insert into public.sales(batch_id, product_id, qty, unit_price, created_by)
  values (v_batch.id, v_batch.product_id, p_qty, p_unit_price, auth.uid());
end;
$$;

revoke all on function public.register_sale(bigint,integer,numeric) from public;
grant execute on function public.register_sale(bigint,integer,numeric) to authenticated;

-- IMPORTANTE:
-- Después de crear tu usuario en Supabase Authentication > Users,
-- ejecuta una línea como esta cambiando el correo:
-- insert into public.allowed_emails(email) values ('TU_CORREO@EJEMPLO.COM')
-- on conflict (email) do nothing;
